### ISSUE TITLE
配置文件求教,大佬能帮我看看嘛?    raise type(e)( ValueError: class `MyDataset` in mmseg/datasets/my_dataset.py: need at least one array to concatenate

### ISSUE THREAD

**Issue by tao-xiaoxin** [TommyZihao/MMSegmentation_Tutorials#5]
以下是我的配置conf.py文件:
```python
dataset_type = 'MyDataset'
data_root = '/root/autodl-tmp/workspace/mmsegmentation/data/'
img_path = 'img-png-1'
seg_map_path = 'lab-png-1'
norm_cfg_type = 'SyncBN'
norm_cfg = dict(type=norm_cfg_type, requires_grad=True)
data_preprocessor = dict(
    type='SegDataPreProcessor',
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    bgr_to_rgb=True,
    pad_val=0,
    seg_pad_val=255,
    size=(512, 512))
model = dict(
    type='EncoderDecoder',
    data_preprocessor=dict(
        type='SegDataPreProcessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_val=0,
        seg_pad_val=255,
        size=(512, 512)),
    pretrained='https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segformer/mit_b5_20220624-658746d9.pth',
    backbone=dict(
        type='MixVisionTransformer',
        in_channels=3,
        embed_dims=64,
        num_stages=4,
        num_layers=[3, 6, 40, 3],
        num_heads=[1, 2, 5, 8],
        patch_sizes=[7, 3, 3, 3],
        sr_ratios=[8, 4, 2, 1],
        out_indices=(0, 1, 2, 3),
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.1),
    decode_head=dict(
        type='SegformerHead',
        in_channels=[64, 128, 320, 512],
        in_index=[0, 1, 2, 3],
        channels=256,
        dropout_ratio=0.1,
        num_classes=6,
        norm_cfg=dict(type=norm_cfg_type, requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))

crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(
        type='RandomResize',
        scale=(2048, 1024),
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='PackSegInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
    dict(type='LoadAnnotations'),
    dict(type='PackSegInputs')
]
img_ratios = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
tta_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(
        type='TestTimeAug',
        transforms=[[{
            'type': 'Resize',
            'scale_factor': 0.5,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 0.75,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.0,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.25,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.5,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.75,
            'keep_ratio': True
        }],
            [{
                'type': 'RandomFlip',
                'prob': 0.0,
                'direction': 'horizontal'
            }, {
                'type': 'RandomFlip',
                'prob': 1.0,
                'direction': 'horizontal'
            }], [{
                'type': 'LoadAnnotations'
            }], [{
                'type': 'PackSegInputs'
            }]])
]

train_dataloader = dict(
    batch_size=4,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(img_path=img_path, seg_map_path=seg_map_path),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(
                type='RandomResize',
                scale=(2048, 1024),
                ratio_range=(0.5, 2.0),
                keep_ratio=True),
            dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(type='PackSegInputs')
        ]))
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(img_path=img_path, seg_map_path=seg_map_path),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ]))
test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(img_path=img_path, seg_map_path=seg_map_path),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ]))

val_evaluator = dict(
    type='IoUMetric', iou_metrics=['mIoU', 'mDice', 'mFscore'])
test_evaluator = dict(
    type='IoUMetric', iou_metrics=['mIoU', 'mDice', 'mFscore'])
default_scope = 'mmseg'
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [
    dict(type='LocalVisBackend'),
    dict(type='TensorboardVisBackend')
]
visualizer = dict(
    type='SegLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        dict(type='TensorboardVisBackend')
    ],
    name='visualizer')
log_processor = dict(by_epoch=False)
log_level = 'INFO'
load_from = None
resume = False
tta_model = dict(type='SegTTAModel')
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW', lr=6e-05, betas=(0.9, 0.999), weight_decay=0.01),
    paramwise_cfg=dict(
        custom_keys=dict(
            pos_block=dict(decay_mult=0.0),
            norm=dict(decay_mult=0.0),
            head=dict(lr_mult=10.0))))
param_scheduler = [
    dict(
        type='LinearLR', start_factor=1e-06, by_epoch=False, begin=0,
        end=1500),
    dict(
        type='PolyLR',
        eta_min=0.0,
        power=1.0,
        begin=1500,
        end=160000,
        by_epoch=False)
]
train_cfg = dict(type='IterBasedTrainLoop', max_iters=40000, val_interval=500)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=100, log_metric_by_epoch=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(
        type='CheckpointHook',
        by_epoch=False,
        interval=2500,
        max_keep_ckpts=2,
        save_best='mIoU'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='SegVisualizationHook'))
work_dir = './work_dirs/Test-Segformer'
randomness = dict(seed=0)
```
然后我的my_dataset.py文件为:
```
from mmseg.registry import DATASETS
from .basesegdataset import BaseSegDataset

@DATASETS.register_module()
class MyDataset(BaseSegDataset):
    # 类别和对应的 RGB配色
    METAINFO = {
        'classes':['background', 'red', 'green', 'white', 'seed-black', 'seed-white'],
        'palette':[[127,127,127], [200,0,0], [0,200,0], [144,238,144], [30,30,30], [251,189,8]]
    }
    
    # 指定图像扩展名、标注扩展名
    def __init__(self,
                 seg_map_suffix='.png',   # 标注mask图像的格式
                 reduce_zero_label=False, # 类别ID为0的类别是否需要除去
                 **kwargs) -> None:
        super().__init__(seg_map_suffix=seg_map_suffix,reduce_zero_label=reduce_zero_label,**kwargs)
```
最后运行python tools/train.py --config conf.py  就报错如下:
```bash
Traceback (most recent call last):
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/autodl-tmp/workspace/mmsegmentation/mmseg/datasets/my_dataset.py", line 17, in __init__
    super().__init__(seg_map_suffix=seg_map_suffix,reduce_zero_label=reduce_zero_label,**kwargs)
  File "/root/autodl-tmp/workspace/mmsegmentation/mmseg/datasets/basesegdataset.py", line 142, in __init__
    self.full_init()
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 305, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 765, in _serialize_data
    data_bytes = np.concatenate(data_list)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    runner.train()
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1701, in train
    self._train_loop = self.build_train_loop(
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1503, in build_train_loop
    loop = IterBasedTrainLoop(
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 219, in __init__
    super().__init__(runner, dataloader)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1351, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
ValueError: class `MyDataset` in mmseg/datasets/my_dataset.py: need at least one array to concatenate
```
大佬们能帮我看看嘛?我应该怎么改呢?

**Comment by tao-xiaoxin** [comment]
> 以下是我的配置conf.py文件:
> 
> ```python
> dataset_type = 'MyDataset'
> data_root = '/root/autodl-tmp/workspace/mmsegmentation/data/'
> img_path = 'img-png-1'
> seg_map_path = 'lab-png-1'
> norm_cfg_type = 'SyncBN'
> norm_cfg = dict(type=norm_cfg_type, requires_grad=True)
> data_preprocessor = dict(
>     type='SegDataPreProcessor',
>     mean=[123.675, 116.28, 103.53],
>     std=[58.395, 57.12, 57.375],
>     bgr_to_rgb=True,
>     pad_val=0,
>     seg_pad_val=255,
>     size=(512, 512))
> model = dict(
>     type='EncoderDecoder',
>     data_preprocessor=dict(
>         type='SegDataPreProcessor',
>         mean=[123.675, 116.28, 103.53],
>         std=[58.395, 57.12, 57.375],
>         bgr_to_rgb=True,
>         pad_val=0,
>         seg_pad_val=255,
>         size=(512, 512)),
>     pretrained='https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segformer/mit_b5_20220624-658746d9.pth',
>     backbone=dict(
>         type='MixVisionTransformer',
>         in_channels=3,
>         embed_dims=64,
>         num_stages=4,
>         num_layers=[3, 6, 40, 3],
>         num_heads=[1, 2, 5, 8],
>         patch_sizes=[7, 3, 3, 3],
>         sr_ratios=[8, 4, 2, 1],
>         out_indices=(0, 1, 2, 3),
>         mlp_ratio=4,
>         qkv_bias=True,
>         drop_rate=0.0,
>         attn_drop_rate=0.0,
>         drop_path_rate=0.1),
>     decode_head=dict(
>         type='SegformerHead',
>         in_channels=[64, 128, 320, 512],
>         in_index=[0, 1, 2, 3],
>         channels=256,
>         dropout_ratio=0.1,
>         num_classes=6,
>         norm_cfg=dict(type=norm_cfg_type, requires_grad=True),
>         align_corners=False,
>         loss_decode=dict(
>             type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
>     train_cfg=dict(),
>     test_cfg=dict(mode='whole'))
> 
> crop_size = (512, 512)
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations'),
>     dict(
>         type='RandomResize',
>         scale=(2048, 1024),
>         ratio_range=(0.5, 2.0),
>         keep_ratio=True),
>     dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
>     dict(type='RandomFlip', prob=0.5),
>     dict(type='PhotoMetricDistortion'),
>     dict(type='PackSegInputs')
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
>     dict(type='LoadAnnotations'),
>     dict(type='PackSegInputs')
> ]
> img_ratios = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
> tta_pipeline = [
>     dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
>     dict(
>         type='TestTimeAug',
>         transforms=[[{
>             'type': 'Resize',
>             'scale_factor': 0.5,
>             'keep_ratio': True
>         }, {
>             'type': 'Resize',
>             'scale_factor': 0.75,
>             'keep_ratio': True
>         }, {
>             'type': 'Resize',
>             'scale_factor': 1.0,
>             'keep_ratio': True
>         }, {
>             'type': 'Resize',
>             'scale_factor': 1.25,
>             'keep_ratio': True
>         }, {
>             'type': 'Resize',
>             'scale_factor': 1.5,
>             'keep_ratio': True
>         }, {
>             'type': 'Resize',
>             'scale_factor': 1.75,
>             'keep_ratio': True
>         }],
>             [{
>                 'type': 'RandomFlip',
>                 'prob': 0.0,
>                 'direction': 'horizontal'
>             }, {
>                 'type': 'RandomFlip',
>                 'prob': 1.0,
>                 'direction': 'horizontal'
>             }], [{
>                 'type': 'LoadAnnotations'
>             }], [{
>                 'type': 'PackSegInputs'
>             }]])
> ]
> 
> train_dataloader = dict(
>     batch_size=4,
>     num_workers=2,
>     persistent_workers=True,
>     sampler=dict(type='InfiniteSampler', shuffle=True),
>     dataset=dict(
>         type=dataset_type,
>         data_root=data_root,
>         data_prefix=dict(img_path=img_path, seg_map_path=seg_map_path),
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(type='LoadAnnotations'),
>             dict(
>                 type='RandomResize',
>                 scale=(2048, 1024),
>                 ratio_range=(0.5, 2.0),
>                 keep_ratio=True),
>             dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
>             dict(type='RandomFlip', prob=0.5),
>             dict(type='PhotoMetricDistortion'),
>             dict(type='PackSegInputs')
>         ]))
> val_dataloader = dict(
>     batch_size=1,
>     num_workers=4,
>     persistent_workers=True,
>     sampler=dict(type='DefaultSampler', shuffle=False),
>     dataset=dict(
>         type=dataset_type,
>         data_root=data_root,
>         data_prefix=dict(img_path=img_path, seg_map_path=seg_map_path),
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
>             dict(type='LoadAnnotations'),
>             dict(type='PackSegInputs')
>         ]))
> test_dataloader = dict(
>     batch_size=1,
>     num_workers=4,
>     persistent_workers=True,
>     sampler=dict(type='DefaultSampler', shuffle=False),
>     dataset=dict(
>         type=dataset_type,
>         data_root=data_root,
>         data_prefix=dict(img_path=img_path, seg_map_path=seg_map_path),
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
>             dict(type='LoadAnnotations'),
>             dict(type='PackSegInputs')
>         ]))
> 
> val_evaluator = dict(
>     type='IoUMetric', iou_metrics=['mIoU', 'mDice', 'mFscore'])
> test_evaluator = dict(
>     type='IoUMetric', iou_metrics=['mIoU', 'mDice', 'mFscore'])
> default_scope = 'mmseg'
> env_cfg = dict(
>     cudnn_benchmark=True,
>     mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
>     dist_cfg=dict(backend='nccl'))
> vis_backends = [
>     dict(type='LocalVisBackend'),
>     dict(type='TensorboardVisBackend')
> ]
> visualizer = dict(
>     type='SegLocalVisualizer',
>     vis_backends=[
>         dict(type='LocalVisBackend'),
>         dict(type='TensorboardVisBackend')
>     ],
>     name='visualizer')
> log_processor = dict(by_epoch=False)
> log_level = 'INFO'
> load_from = None
> resume = False
> tta_model = dict(type='SegTTAModel')
> optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
> optim_wrapper = dict(
>     type='OptimWrapper',
>     optimizer=dict(
>         type='AdamW', lr=6e-05, betas=(0.9, 0.999), weight_decay=0.01),
>     paramwise_cfg=dict(
>         custom_keys=dict(
>             pos_block=dict(decay_mult=0.0),
>             norm=dict(decay_mult=0.0),
>             head=dict(lr_mult=10.0))))
> param_scheduler = [
>     dict(
>         type='LinearLR', start_factor=1e-06, by_epoch=False, begin=0,
>         end=1500),
>     dict(
>         type='PolyLR',
>         eta_min=0.0,
>         power=1.0,
>         begin=1500,
>         end=160000,
>         by_epoch=False)
> ]
> train_cfg = dict(type='IterBasedTrainLoop', max_iters=40000, val_interval=500)
> val_cfg = dict(type='ValLoop')
> test_cfg = dict(type='TestLoop')
> default_hooks = dict(
>     timer=dict(type='IterTimerHook'),
>     logger=dict(type='LoggerHook', interval=100, log_metric_by_epoch=False),
>     param_scheduler=dict(type='ParamSchedulerHook'),
>     checkpoint=dict(
>         type='CheckpointHook',
>         by_epoch=False,
>         interval=2500,
>         max_keep_ckpts=2,
>         save_best='mIoU'),
>     sampler_seed=dict(type='DistSamplerSeedHook'),
>     visualization=dict(type='SegVisualizationHook'))
> work_dir = './work_dirs/Test-Segformer'
> randomness = dict(seed=0)
> ```
> 
> 然后我的my_dataset.py文件为:
> 
> ```
> from mmseg.registry import DATASETS
> from .basesegdataset import BaseSegDataset
> 
> @DATASETS.register_module()
> class MyDataset(BaseSegDataset):
>     # 类别和对应的 RGB配色
>     METAINFO = {
>         'classes':['background', 'red', 'green', 'white', 'seed-black', 'seed-white'],
>         'palette':[[127,127,127], [200,0,0], [0,200,0], [144,238,144], [30,30,30], [251,189,8]]
>     }
>     
>     # 指定图像扩展名、标注扩展名
>     def __init__(self,
>                  seg_map_suffix='.png',   # 标注mask图像的格式
>                  reduce_zero_label=False, # 类别ID为0的类别是否需要除去
>                  **kwargs) -> None:
>         super().__init__(seg_map_suffix=seg_map_suffix,reduce_zero_label=reduce_zero_label,**kwargs)
> ```
> 
> 最后运行python tools/train.py --config conf.py 就报错如下:
> 
> ```shell
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
>     obj = obj_cls(**args)  # type: ignore
>   File "/root/autodl-tmp/workspace/mmsegmentation/mmseg/datasets/my_dataset.py", line 17, in __init__
>     super().__init__(seg_map_suffix=seg_map_suffix,reduce_zero_label=reduce_zero_label,**kwargs)
>   File "/root/autodl-tmp/workspace/mmsegmentation/mmseg/datasets/basesegdataset.py", line 142, in __init__
>     self.full_init()
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 305, in full_init
>     self.data_bytes, self.data_address = self._serialize_data()
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 765, in _serialize_data
>     data_bytes = np.concatenate(data_list)
>   File "<__array_function__ internals>", line 200, in concatenate
> ValueError: need at least one array to concatenate
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 108, in <module>
>     main()
>   File "tools/train.py", line 104, in main
>     runner.train()
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1701, in train
>     self._train_loop = self.build_train_loop(
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1503, in build_train_loop
>     loop = IterBasedTrainLoop(
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 219, in __init__
>     super().__init__(runner, dataloader)
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
>     self.dataloader = runner.build_dataloader(
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1351, in build_dataloader
>     dataset = DATASETS.build(dataset_cfg)
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
>     return self.build_func(cfg, *args, **kwargs, registry=self)
>   File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
>     raise type(e)(
> ValueError: class `MyDataset` in mmseg/datasets/my_dataset.py: need at least one array to concatenate
> ```
> 
> 大佬们能帮我看看嘛?我应该怎么改呢?
